drop policy "Enable INSERT for authenticated" on "public"."player_hero_stats";

alter table "public"."players" drop constraint "players_user_id_fkey";


  create table "public"."test_table" (
    "id" bigint generated by default as identity not null,
    "name" text
      );


alter table "public"."test_table" enable row level security;

CREATE UNIQUE INDEX players_user_id_key ON public.players USING btree (user_id);

CREATE UNIQUE INDEX test_table_pkey ON public.test_table USING btree (id);

alter table "public"."test_table" add constraint "test_table_pkey" PRIMARY KEY using index "test_table_pkey";

alter table "public"."players" add constraint "players_user_id_key" UNIQUE using index "players_user_id_key";

alter table "public"."players" add constraint "players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."players" validate constraint "players_user_id_fkey";

grant delete on table "public"."test_table" to "anon";

grant insert on table "public"."test_table" to "anon";

grant references on table "public"."test_table" to "anon";

grant select on table "public"."test_table" to "anon";

grant trigger on table "public"."test_table" to "anon";

grant truncate on table "public"."test_table" to "anon";

grant update on table "public"."test_table" to "anon";

grant delete on table "public"."test_table" to "authenticated";

grant insert on table "public"."test_table" to "authenticated";

grant references on table "public"."test_table" to "authenticated";

grant select on table "public"."test_table" to "authenticated";

grant trigger on table "public"."test_table" to "authenticated";

grant truncate on table "public"."test_table" to "authenticated";

grant update on table "public"."test_table" to "authenticated";

grant delete on table "public"."test_table" to "service_role";

grant insert on table "public"."test_table" to "service_role";

grant references on table "public"."test_table" to "service_role";

grant select on table "public"."test_table" to "service_role";

grant trigger on table "public"."test_table" to "service_role";

grant truncate on table "public"."test_table" to "service_role";

grant update on table "public"."test_table" to "service_role";


  create policy "Enable DELETE for authenticated"
  on "public"."player_hero_stats"
  as permissive
  for delete
  to authenticated
using ((last_updated_by = auth.uid()));



  create policy "Enable INSERT for creators"
  on "public"."player_hero_stats"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = last_updated_by));



